name:  Action Workflow 
on: [push, pull_request]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
    
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REF
          echo $GITHUB_REF_NAME
          echo "${{ github.token }}"
          
        #git clone git@github:$GITHUB_REPOSITORY

      - name: Checkout 
        uses: actions/checkout@v1

      - name: List files
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        #uses: actions/hellow-world-javascript-action@master -- branch
        uses: actions/hello-world-javascript-action@v1.1
        #uses: actions/hellow-world-javascript-action@<commit_id> -- commit id
        with: 
          who-to-greet: Supreeth
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time}}"
  