name: New Action workflow
on:
  repository_dispatch:
  # schedule:
  #   - cron: "0/5 * * * * "
  #   - cron: "0/6 * * * * "
  #push:
  pull_request:
    types: [closed, assigned, opened, reopened]
jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
    
      - name: List files
        run: |
          pwd
          ls -a
          echo $GITHUB_SHA
          echo $GITHUB_REPOSITORY
          echo $GITHUB_WORKSPACE
          echo $GITHUB_REF
          echo "To which its getting merged" $GITHUB_REF_NAME
          echo "The current branch name" $GITHUB_HEAD_REF
          echo "${{ github.token }}"
          
        #git clone git@github:$GITHUB_REPOSITORY

      - name: Checkout 
        uses: actions/checkout@v1

      - name: List files
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        #uses: actions/hellow-world-javascript-action@master -- branch
        uses: actions/hello-world-javascript-action@v1.1
        #uses: actions/hellow-world-javascript-action@<commit_id> -- commit id
        with: 
          who-to-greet: Supreeth
      - name: Log Greeting time
        run: echo "${{steps.greet.outputs.time}}"
  