name: Env variables
on: push
env: 
  WF_ENV: Avaible to all jobs 
jobs:
  log-env:
     runs-on: ubuntu-latest
     env:
       JOB_ENV: Only for log-env job
     steps: 
        - name: Log ENV variable
          env:
            STEP_ENV: Only for this step
          run: | 
            echo "WF_ENV: ${WF_ENV}"
            echo "JOB_ENV: ${JOB_ENV}"
            echo "STEP_ENV: ${STEP_ENV}"
        - name: Log Env 2
          run: | 
            echo "WF_ENV: ${WF_ENV}"
            echo "JOB_ENV: ${JOB_ENV}"
            echo "STEP_ENV: ${STEP_ENV}"
  log-default-job:
    runs-on: ubuntu-latest
    steps:
      - name: Default Env Variables
        run: | 
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_WORKSPACE:${GITHUB_WORKSPACE}"
          echo "GITHUB_REF:${GITHUB_REF}"
          echo "GITHUB_ACTION:${GITHUB_ACTION}"
          echo "GITHUB_ACTION_PATH:${GITHUB_ACTION_PATH}"
          echo "GITHUB_ACTION_REPOSITORY:${GITHUB_ACTION_REPOSITORY}"
          echo "GITHUB_ACTIONS:${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR:${GITHUB_ACTOR}"
          echo "GITHUB_ENV:${GITHUB_ENV}"
          echo "GITHUB_EVENT_NAME:${GITHUB_EVENT_NAME}"
          echo "GITHUB_EVENT_PATH:${GITHUB_EVENT_PATH}"
          echo "GITHUB_JOB:${GITHUB_JOB}"
          echo "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          echo "RUNNER_NAME:${RUNNER_NAME}"

          echo "To which its getting merged" $GITHUB_REF_NAME
          echo "The current branch name" $GITHUB_HEAD_REF
